### ISSUE TITLE
GCC编译示例代码1报错

### ISSUE THREAD

**Issue by FragrantRye** [Nomango/jsonxx#10]
$ g++ test.cpp -I jsonxx/include/
> test.cpp:17:8: error: explicit specialization of ‘template<class _Ty, class _BasicJsonTy, typename std::enable_if<jsonxx::is_basic_json<_BasicJsonTy>::value, int>::type <anonymous> > struct jsonxx::json_bind’ outside its namespace must use a nested-name-specifier [-fpermissive]
>    17 | struct json_bind<User> {
>       |        ^~~~~~~~~~~~~~~

**Comment by FragrantRye** [comment]
g++ 版本9.3.0

**Comment by FragrantRye** [comment]
目测是由于gcc不允许命名空间外显示全特化模板导致的，这一点vs支持。
用namespace jsonxx{} 把struct json_bind<User>包起来就好了

**Comment by Nomango** [comment]
示例代码尽量保持精简，没有适配所有编译器，特定编译器的问题case by case的解决吧，issue先关闭了

**Comment by Nomango** [comment]
问题已修复
