### ISSUE TITLE
json序列化时格式出错

### ISSUE THREAD

**Issue by banjuanshua** [Nomango/jsonxx#11]
感谢提供的库，目前遇到这个问题：
对于很小的数使用.dump()序列化后输出

0.005971148862641366^@
-0.00588644005111258^@P
-0.00740774794383903^@o

**Comment by Nomango** [comment]
应该是打印成科学计数法了，回头想想有没有解决办法

**Comment by banjuanshua** [comment]
多谢，换成rapidjson解决了。。。

**Comment by Nomango** [comment]
@banjuanshua 找到问题了，是小浮点数打印科学计数法时，分配的buffer不够，现在已经修复了，测试用例也补充上了，https://github.com/Nomango/jsonxx/blob/a7c032516bc550570f9247fa48c685e5e64037c6/test/test_serializer.cpp#L83
