### ISSUE TITLE
可以支持int64么

### ISSUE THREAD

**Issue by windzxa** [Nomango/jsonxx#12]
可以支持int64么

**Comment by Nomango** [comment]
@windzxa 支持的，默认json使用32位，需要64位的话需要下面的用法：
```cpp
using json64 = jsonxx::basic_json<std::map, std::vector, std::string, std::int64_t, double, bool>;

json64 j = int64_t(1);
j.as_int();  // 返回的类型为 int64_t
```

刚刚补充了简单测试：https://github.com/Nomango/jsonxx/blob/f13c3e2c579c1192c18a4a9c4d8d86beca85629b/test/test_basic_json.cpp#L140
