### ISSUE TITLE
咨询：怎样构造int64的json

### ISSUE THREAD

**Issue by mofywong** [Nomango/jsonxx#18]
请教下如何构建value为int64类型的json。
我如下写法ts会超出范围：
jsonxx::json j = {
        {"msgId", “12345”},
        {"ts", 1621835751000},
    };
    std::string strSend = j.dump();

**Comment by Nomango** [comment]
使用json64代替json即可

**Comment by mofywong** [comment]
> 使用json64代替json即可

感谢，更新新版本有了json64了，之前的版本没搜到。
