### ISSUE TITLE
转成json 后值发生了变化

### ISSUE THREAD

**Issue by guishilike** [Nomango/jsonxx#19]
原本值为float，转为json后位数发生改变
![image](https://user-images.githubusercontent.com/51023060/119760476-a8435680-bedc-11eb-8a8d-0fc3a18e5bd8.png)

**Comment by Nomango** [comment]
@guishilike 浮点数在计算机中是很难准确表示的，jsonxx对浮点数也仅仅只做了简单赋值。可以提供下测试代码看看

**Comment by guishilike** [comment]
- 操作系统：win10
- IDE: Visual Studio 2019 

测试代码如下：
float 精度低，一般来说有效数字 6-7位，现在明显超了

```
#include <iostream>
#include <string>
#include "jsonxx/json.hpp"
using namespace jsonxx;

int main() {

	json res;
	float f = float(512.52);
        res = f;

	std::cout << "real value:" << f << std::endl;
	std::cout << "json:" << res << std::endl;
}
```

![image](https://user-images.githubusercontent.com/51023060/120127779-e5685b00-c1f2-11eb-83ac-bd018627791d.png)
![image](https://user-images.githubusercontent.com/51023060/120127875-30826e00-c1f3-11eb-8af2-10d82fec33d6.png)
而且会用科学计数法表示(实际在用json时还是希望是非科学计数法)
![image](https://user-images.githubusercontent.com/51023060/120127972-7dfedb00-c1f3-11eb-93c1-975fa889d9ee.png)

**Comment by Nomango** [comment]
@guishilike std::cout对浮点数的输出做了处理，下面的case更能说明原因
```cpp
std::cout << "real value:" << f << std::endl;
std::cout << "real value:" << std::fixed << f << std::defaultfloat << std::endl;
std::cout << "json:" << res << std::endl;
std::cout << "json:" << res.as_float() << std::endl;
// output:
// real value:512.52
// real value:512.520020
// json:512.52001953125
// json:512.52
```
对于小浮点数会输出科学计数法是因为jsonxx使用了 sprintf("%.*g", f) 的格式来打印，目前没有提供开关来控制是否启用，建议对这种情况还是使用科学计数法的，使用更少的字符保留更多的数据。

浮点数的问题我在考虑要不要自己实现一个streambuf来达到和std::cout一样的打印效果，issue先保留吧，感谢反馈

**Comment by guishilike** [comment]
![image](https://user-images.githubusercontent.com/51023060/120191691-d44c3800-c24c-11eb-8748-6832f7efd999.png)
std::cout默认截断机制会有损失。
![image](https://user-images.githubusercontent.com/51023060/120192111-5ccad880-c24d-11eb-985f-a62ec59ef696.png)
测试0.125倍数小数，可以正确显示，但是再dump_float时会在后续位置产生垃圾。

**Comment by Nomango** [comment]
@guishilike 最新版本中完善了精度支持，示例代码如下

```cpp
std::cout << "real value: " << f << std::endl;
std::cout << "json: " << res << std::endl;
std::cout << "json with precision: " << std::setprecision(12) << res << std::endl;
```

输出的结果为

```
real value: 512.52
json: 512.52
json with precision: 512.520019531
```

现在jsonxx可以正确的反应 `std::setprecision` 了！

**Comment by guishilike** [comment]
![image](https://user-images.githubusercontent.com/51023060/120281814-006ac600-c2ec-11eb-8061-0fa624e6ecd7.png)
但是在转为字符串后依旧是原先的位数

**Comment by Nomango** [comment]
@guishilike dump可以通过参数指定精度，类似这样

```cpp
json::dump_args args;
args.precision = 6; // 设置精度为6位，std::cout的默认精度
j.dump(args);
```

**Comment by Nomango** [comment]
@guishilike 没有其他问题的话先关闭了
