### ISSUE TITLE
namespace "std" has no member "isdigit"

### ISSUE THREAD

**Issue by ifsheldon** [Nomango/jsonxx#6]
我在用VS17的build tool和nvcc在Windows10上编译的时候会出现`namespace "std" has no member "isdigit"`这个error，然后在[cpp reference](https://en.cppreference.com/w/cpp/string/byte/isdigit)上查到isdigit这个是在<cctype>里面的，在json_parser.hpp里加上`include <cctype>`就可以编译通过了，建议在json_parser.hpp里加上这一行

**Comment by Nomango** [comment]
@ifsheldon 感谢反馈，已修复
