### ISSUE TITLE
中文转换乱码的问题

### ISSUE THREAD

**Issue by xuanyuan1hao** [Nomango/jsonxx#8]
代码如下：
json j;
	char * BrokerID = "测试中文";
	j["BrokerID"] = BrokerID;
	std::string json_str = j.dump();

生成json为：
{"BrokerID":"\uffb2\uffe2\uffca\uffd4\uffd6\uffd0\uffce\uffc4"}

这里生成的unicode编码使用站长工具的unicode转中文工具，转换出来是乱码

**Comment by Nomango** [comment]
@xuanyuan1hao 这个是因为jsonxx没有支持[辅助平面中的码位](https://zh.wikipedia.org/wiki/UTF-16#%E4%BB%8EU+10000%E5%88%B0U+10FFFF%E7%9A%84%E7%A0%81%E4%BD%8D)

**Comment by Nomango** [comment]
@xuanyuan1hao 最新的版本已修复该问题，示例代码：
```cpp
json j = "我是地球🌍";

// 不转义utf-8字符
cout << j.dump(-1, ' ', false);  // "我是地球🌍"
// 转义utf-8字符
cout << j.dump(-1, ' ', true);  // "\u6211\u662F\u5730\u7403\uD83C\uDF0D"
```
