### ISSUE TITLE
多级json中文出现乱码

### ISSUE THREAD

**Issue by ztkboj58623** [Nomango/jsonxx#9]
struct Config
{
  std::string name;
}

Config config;
config.name = XXX;//从MySQL中取值，MySQL设置了字符集为utf8，假定XXX=“中国”，此时debug时看到的name就是乱码的

json test;
test["test"] ="中文Test123434";
test["config"] = config;

test.dump()的结果，name显示中国，但"中文Test123434"却显示乱码了，请问该如何处理？

结果是以res.set_content(json_result.dump(), "text/plain");形式返回的

**Comment by Nomango** [comment]
是的，utf8编码的字符串在C++中应使用std::wstring，需要转换成std::string才可以在jsonxx中使用

**Comment by Nomango** [comment]
问题已在最新版修复
